---
# Configure redis

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ redis_services_enable }}"
  when: redis_enable_service
