---
# Install redis packages

- name: unwanted packages are removed
  package:
    name: "{{ redis_packages_remove }}"
    state: absent
  become: true
  when: redis_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ redis_packages_repos }}"
    state: "{{ redis_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ redis_packages_prereq }}"
    state: "{{ redis_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ redis_packages_install }}"
    state: "{{ redis_packages_state }}"
  become: true
