---
# Template configuration files for redis

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ redis_templates_copy }}"
  when: redis_copy_templates
